"""
memory.py — Writes every signal and trade outcome to Obsidian.

Structure inside the vault:
  Trading/
    Signals/       YYYY-MM-DD_TICKER.md   (created at signal time)
    Learnings/     YYYY-MM-DD_TICKER.md   (written when outcome is logged)
"""

import os
from datetime import datetime
from pathlib import Path

VAULT = Path(os.getenv("OBSIDIAN_VAULT_PATH", ""))


def _ensure(path: Path):
    path.mkdir(parents=True, exist_ok=True)


def write_signal(decision: dict, scan_data: dict):
    """Write a new signal note immediately when Claude fires SIGNAL."""
    if not VAULT.name:
        return

    signals_dir = VAULT / "Trading" / "Signals"
    _ensure(signals_dir)

    ticker = decision.get("ticker", "UNKNOWN")
    date_str = datetime.now().strftime("%Y-%m-%d")
    filename = signals_dir / f"{date_str}_{ticker}.md"

    content = f"""# Signal — {ticker} — {date_str}

## Setup
- **Price at signal:** ${scan_data.get("price", "n/a")}
- **Volume ratio:** {scan_data.get("vol_ratio", "n/a")}x
- **RSI:** {scan_data.get("rsi", "n/a")}
- **5-day return:** {scan_data.get("ret_5d", "n/a")}%
- **Scanner signals:** {scan_data.get("reasons", "n/a")}

## Claude's Thesis
{decision.get("thesis", "")}

## Trade Plan
| | |
|---|---|
| Entry zone | {decision.get("entry", "n/a")} |
| Stop | {decision.get("stop", "n/a")} |
| Target 1 | {decision.get("target1", "n/a")} |
| Target 2 | {decision.get("target2", "n/a")} |

## Outcome
*(fill in after trade closes)*

- Exit price:
- P&L:
- What worked:
- What didn't:
- Learning:

---
*Generated by Trading Bot*
"""
    filename.write_text(content, encoding="utf-8")
    print(f"[memory] Signal note written: {filename.name}")


def write_watchlist(decision: dict, scan_data: dict):
    """Write a watchlist note."""
    if not VAULT.name:
        return

    watchlist_dir = VAULT / "Trading" / "Watchlist"
    _ensure(watchlist_dir)

    ticker = decision.get("ticker", "UNKNOWN")
    date_str = datetime.now().strftime("%Y-%m-%d")
    filename = watchlist_dir / f"{date_str}_{ticker}.md"

    content = f"""# Watchlist — {ticker} — {date_str}

- **Price:** ${scan_data.get("price", "n/a")}
- **Volume ratio:** {scan_data.get("vol_ratio", "n/a")}x
- **RSI:** {scan_data.get("rsi", "n/a")}

## Watching for
{decision.get("thesis", "")}

---
*Generated by Trading Bot*
"""
    filename.write_text(content, encoding="utf-8")
    print(f"[memory] Watchlist note written: {filename.name}")


def write_learning(ticker: str, exit_price: float, pnl_pct: float, notes: str):
    """
    Call this manually (or via a Discord command later) when a trade closes.
    Writes a learning note Claude will re-read before future analysis.
    """
    if not VAULT.name:
        return

    learnings_dir = VAULT / "Trading" / "Learnings"
    _ensure(learnings_dir)

    date_str = datetime.now().strftime("%Y-%m-%d")
    filename = learnings_dir / f"{date_str}_{ticker}.md"

    outcome = "WIN" if pnl_pct > 0 else "LOSS"
    content = f"""# Learning — {ticker} — {date_str} ({outcome})

- **Exit price:** ${exit_price}
- **P&L:** {pnl_pct:+.1f}%

## Notes
{notes}

---
*Written by Trading Bot — re-read before every analysis*
"""
    filename.write_text(content, encoding="utf-8")
    print(f"[memory] Learning note written: {filename.name}")
